// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *character → gallery*
 */
export interface CharacterDocumentDataGalleryItem {
  /**
   * image field in *character → gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: character.gallery[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * caption field in *character → gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: character.gallery[].caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  caption: prismic.KeyTextField;
}

/**
 * Item in *character → relations*
 */
export interface CharacterDocumentDataRelationsItem {
  /**
   * character_ref field in *character → relations*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: character.relations[].character_ref
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  character_ref: prismic.ContentRelationshipField<"character">;

  /**
   * note field in *character → relations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: character.relations[].note
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  note: prismic.KeyTextField;
}

type CharacterDocumentDataSlicesSlice = never;

/**
 * Content for character documents
 */
interface CharacterDocumentData {
  /**
   * name field in *character*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: character.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * portrait field in *character*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: character.portrait
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  portrait: prismic.ImageField<never>;

  /**
   * role field in *character*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: character.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  role: prismic.SelectField<
    "Protagonist" | "Ally" | "Antagonist" | "Neutral" | "Other"
  >;

  /**
   * short_bio field in *character*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: character.short_bio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_bio: prismic.RichTextField;

  /**
   * gallery field in *character*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: character.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery: prismic.GroupField<Simplify<CharacterDocumentDataGalleryItem>>;

  /**
   * relations field in *character*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: character.relations[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  relations: prismic.GroupField<Simplify<CharacterDocumentDataRelationsItem>>;

  /**
   * Slice Zone field in *character*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: character.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<CharacterDocumentDataSlicesSlice>; /**
   * meta_title field in *character*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: character.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * meta_description field in *character*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: character.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  meta_description: prismic.RichTextField;

  /**
   * meta_image field in *character*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: character.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * noindex field in *character*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: character.noindex
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  noindex: prismic.BooleanField;
}

/**
 * character document from Prismic
 *
 * - **API ID**: `character`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CharacterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CharacterDocumentData>,
    "character",
    Lang
  >;

/**
 * Item in *episode → tags*
 */
export interface EpisodeDocumentDataTagsItem {
  /**
   * tag field in *episode → tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag: prismic.KeyTextField;
}

/**
 * Item in *episode → characters*
 */
export interface EpisodeDocumentDataCharactersItem {
  /**
   * character_ref field in *episode → characters*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.characters[].character_ref
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  character_ref: prismic.ContentRelationshipField<"character">;
}

type EpisodeDocumentDataSlicesSlice = ExternalSupportSlice;

/**
 * Content for episode documents
 */
interface EpisodeDocumentData {
  /**
   * title field in *episode*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * chapter_number field in *episode*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.chapter_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  chapter_number: prismic.NumberField;

  /**
   * publish_date field in *episode*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.publish_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  publish_date: prismic.DateField;

  /**
   * cover field in *episode*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.cover
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover: prismic.ImageField<never>;

  /**
   * summary field in *episode*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  summary: prismic.RichTextField;

  /**
   * tags field in *episode*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.tags[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tags: prismic.GroupField<Simplify<EpisodeDocumentDataTagsItem>>;

  /**
   * arc field in *episode*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Prologue
   * - **API ID Path**: episode.arc
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  arc: prismic.SelectField<"Prologue" | "Arc I", "filled">;

  /**
   * characters field in *episode*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.characters[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  characters: prismic.GroupField<Simplify<EpisodeDocumentDataCharactersItem>>;

  /**
   * Slice Zone field in *episode*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<EpisodeDocumentDataSlicesSlice>; /**
   * meta_title field in *episode*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * meta_description field in *episode*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  meta_description: prismic.RichTextField;

  /**
   * meta_image field in *episode*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: episode.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * noindex field in *episode*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: episode.noindex
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  noindex: prismic.BooleanField;
}

/**
 * episode document from Prismic
 *
 * - **API ID**: `episode`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EpisodeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EpisodeDocumentData>,
    "episode",
    Lang
  >;

type EpisodesIndexDocumentDataSlicesSlice = never;

/**
 * Content for episodes_index documents
 */
interface EpisodesIndexDocumentData {
  /**
   * intro_richtext field in *episodes_index*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episodes_index.intro_richtext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro_richtext: prismic.RichTextField;

  /**
   * filter_toggle field in *episodes_index*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: episodes_index.filter_toggle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  filter_toggle: prismic.BooleanField;

  /**
   * grid_layout field in *episodes_index*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: episodes_index.grid_layout
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  grid_layout: prismic.SelectField<"threeCols" | "fourCols" | "masonry">;

  /**
   * Slice Zone field in *episodes_index*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: episodes_index.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<EpisodesIndexDocumentDataSlicesSlice>; /**
   * meta_title field in *episodes_index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episodes_index.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * meta_description field in *episodes_index*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: episodes_index.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  meta_description: prismic.RichTextField;

  /**
   * meta_image field in *episodes_index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: episodes_index.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * noindex field in *episodes_index*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: episodes_index.noindex
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  noindex: prismic.BooleanField;
}

/**
 * episodes_index document from Prismic
 *
 * - **API ID**: `episodes_index`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EpisodesIndexDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EpisodesIndexDocumentData>,
    "episodes_index",
    Lang
  >;

/**
 * Item in *home → hero_cta*
 */
export interface HomeDocumentDataHeroCtaItem {
  /**
   * label field in *home → hero_cta*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_cta[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *home → hero_cta*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_cta[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *home → featured_episodes*
 */
export interface HomeDocumentDataFeaturedEpisodesItem {
  /**
   * episode_ref field in *home → featured_episodes*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: home.featured_episodes[].episode_ref
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  episode_ref: prismic.ContentRelationshipField<"episode">;
}

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * hero_image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * hero_kicker field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_kicker
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_kicker: prismic.KeyTextField;

  /**
   * hero_cta field in *home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_cta[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  hero_cta: prismic.GroupField<Simplify<HomeDocumentDataHeroCtaItem>>;

  /**
   * featured_episodes field in *home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.featured_episodes[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  featured_episodes: prismic.GroupField<
    Simplify<HomeDocumentDataFeaturedEpisodesItem>
  >;

  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * meta_title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * meta_description field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  meta_description: prismic.RichTextField;

  /**
   * meta_image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * noindex field in *home*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: home.noindex
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  noindex: prismic.BooleanField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type LoreEntryDocumentDataSlicesSlice = never;

/**
 * Content for lore_entry documents
 */
interface LoreEntryDocumentData {
  /**
   * title field in *lore_entry*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lore_entry.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * cover field in *lore_entry*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: lore_entry.cover
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover: prismic.ImageField<never>;

  /**
   * category field in *lore_entry*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: lore_entry.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<
    | "Locations"
    | "Factions"
    | "Tech"
    | "Creatures"
    | "History"
    | "Culture"
    | "Systems"
  >;

  /**
   * short_intro field in *lore_entry*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lore_entry.short_intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_intro: prismic.RichTextField;

  /**
   * Slice Zone field in *lore_entry*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: lore_entry.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LoreEntryDocumentDataSlicesSlice>; /**
   * meta_title field in *lore_entry*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lore_entry.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * meta_description field in *lore_entry*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lore_entry.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  meta_description: prismic.RichTextField;

  /**
   * meta_image field in *lore_entry*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: lore_entry.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * noindex field in *lore_entry*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: lore_entry.noindex
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  noindex: prismic.BooleanField;
}

/**
 * lore_entry document from Prismic
 *
 * - **API ID**: `lore_entry`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LoreEntryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LoreEntryDocumentData>,
    "lore_entry",
    Lang
  >;

type NavDocumentDataSlicesSlice = never;

/**
 * Content for Nav documents
 */
interface NavDocumentData {
  /**
   * Slice Zone field in *Nav*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<NavDocumentDataSlicesSlice>; /**
   * Meta Title field in *Nav*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: nav.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Nav*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: nav.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Nav*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<NavDocumentData>, "nav", Lang>;

/**
 * Item in *Navigation → primary_links*
 */
export interface NavigationDocumentDataPrimaryLinksItem {
  /**
   * label field in *Navigation → primary_links*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.primary_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  label: prismic.RichTextField;

  /**
   * link field in *Navigation → primary_links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.primary_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * icon_image field in *Navigation → primary_links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.primary_links[].icon_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon_image: prismic.ImageField<never>;

  /**
   * icon_alt_override field in *Navigation → primary_links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.primary_links[].icon_alt_override
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_alt_override: prismic.KeyTextField;

  /**
   * icon_position field in *Navigation → primary_links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.primary_links[].icon_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon_position: prismic.SelectField<"left" | "right">;

  /**
   * hide_label field in *Navigation → primary_links*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: navigation.primary_links[].hide_label
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  hide_label: prismic.BooleanField;
}

/**
 * Item in *Navigation → secondary_links*
 */
export interface NavigationDocumentDataSecondaryLinksItem {
  /**
   * label field in *Navigation → secondary_links*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.secondary_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  label: prismic.RichTextField;

  /**
   * link field in *Navigation → secondary_links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.secondary_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * primary_links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.primary_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  primary_links: prismic.GroupField<
    Simplify<NavigationDocumentDataPrimaryLinksItem>
  >;

  /**
   * secondary_links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.secondary_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  secondary_links: prismic.GroupField<
    Simplify<NavigationDocumentDataSecondaryLinksItem>
  >; /**
   * meta_title field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * meta_description field in *Navigation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  meta_description: prismic.RichTextField;

  /**
   * meta_image field in *Navigation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * noindex field in *Navigation*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: navigation.noindex
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  noindex: prismic.BooleanField;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  parent: prismic.ContentRelationshipField<"page">;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * meta_image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * og_image_override field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.og_image_override
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image_override: prismic.ImageField<never>;

  /**
   * noindex field in *Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: page.noindex
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  noindex: prismic.BooleanField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → brand*
 */
export interface SettingsDocumentDataBrandItem {
  /**
   * label field in *Settings → brand*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.brand[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *Settings → brand*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.brand[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * icon_image field in *Settings → brand*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.brand[].icon_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon_image: prismic.ImageField<never>;

  /**
   * icon_alt_override field in *Settings → brand*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.brand[].icon_alt_override
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_alt_override: prismic.KeyTextField;

  /**
   * icon_position field in *Settings → brand*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.brand[].icon_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon_position: prismic.SelectField<"left" | "right">;

  /**
   * hide_label field in *Settings → brand*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.brand[].hide_label
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  hide_label: prismic.BooleanField;
}

/**
 * Item in *Settings → social_links*
 */
export interface SettingsDocumentDataSocialLinksItem {
  /**
   * label field in *Settings → social_links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * url field in *Settings → social_links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * icon_key field in *Settings → social_links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[].icon_key
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon_key: prismic.SelectField<
    | "X"
    | "instagram"
    | "tumblr"
    | "webtoon"
    | "tapas"
    | "youtube"
    | "tiktok"
    | "discord"
    | "github"
    | "other"
  >;
}

/**
 * Item in *Settings → store_links*
 */
export interface SettingsDocumentDataStoreLinksItem {
  /**
   * label field in *Settings → store_links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.store_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * url field in *Settings → store_links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.store_links[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Settings → newsletter*
 */
export interface SettingsDocumentDataNewsletterItem {
  /**
   * provider field in *Settings → newsletter*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsletter[].provider
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  provider: prismic.SelectField<
    "Beehiiv" | "Mailchimp" | "Buttondown" | "Netlify"
  >;

  /**
   * embed field in *Settings → newsletter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsletter[].embed
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  embed: prismic.KeyTextField;

  /**
   * url field in *Settings → newsletter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsletter[].url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  url: prismic.KeyTextField;

  /**
   * cta_label field in *Settings → newsletter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsletter[].cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * site_title field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  site_title: prismic.RichTextField;

  /**
   * brand field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.brand[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  brand: prismic.GroupField<Simplify<SettingsDocumentDataBrandItem>>;

  /**
   * logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * og_default field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_default
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_default: prismic.ImageField<never>;

  /**
   * footer_text field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_text: prismic.RichTextField;

  /**
   * social_links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<
    Simplify<SettingsDocumentDataSocialLinksItem>
  >;

  /**
   * store_links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.store_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  store_links: prismic.GroupField<Simplify<SettingsDocumentDataStoreLinksItem>>;

  /**
   * newsletter field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsletter[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  newsletter: prismic.GroupField<
    Simplify<SettingsDocumentDataNewsletterItem>
  >; /**
   * meta_title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * meta_description field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  meta_description: prismic.RichTextField;

  /**
   * meta_image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * noindex field in *Settings*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.noindex
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  noindex: prismic.BooleanField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type TestDocumentDataSlicesSlice = ExternalSupportSlice;

/**
 * Content for Test documents
 */
interface TestDocumentData {
  /**
   * Slice Zone field in *Test*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: test.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<TestDocumentDataSlicesSlice>; /**
   * Meta Title field in *Test*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: test.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Test*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: test.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Test*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: test.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Test document from Prismic
 *
 * - **API ID**: `test`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<TestDocumentData>, "test", Lang>;

export type AllDocumentTypes =
  | CharacterDocument
  | EpisodeDocument
  | EpisodesIndexDocument
  | HomeDocument
  | LoreEntryDocument
  | NavDocument
  | NavigationDocument
  | PageDocument
  | SettingsDocument
  | TestDocument;

/**
 * Primary content in *ExternalSupport → Row of buttons → Primary*
 */
export interface ExternalSupportSliceRowPrimary {
  /**
   * Title (optional) field in *ExternalSupport → Row of buttons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.row.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Intro (optional) field in *ExternalSupport → Row of buttons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.row.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *ExternalSupport → Items*
 */
export interface ExternalSupportSliceRowItem {
  /**
   * Platform field in *ExternalSupport → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.items[].platform
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  platform: prismic.SelectField<
    "Patreon" | "Kickstarter" | "Ko-fi" | "Discord" | "YouTube" | "Other"
  >;

  /**
   * Button label (e.g. 'Back us on Kickstarter') field in *ExternalSupport → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Short description (used in 'cards' variation) field in *ExternalSupport → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Destination URL field in *ExternalSupport → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.items[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon / mark (square, transparent) field in *ExternalSupport → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Accent color (overrides ember) field in *ExternalSupport → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.items[].accent
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  accent: prismic.ColorField;
}

/**
 * Row of buttons variation for ExternalSupport Slice
 *
 * - **API ID**: `row`
 * - **Description**: Horizontal strip of platform buttons.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExternalSupportSliceRow = prismic.SharedSliceVariation<
  "row",
  Simplify<ExternalSupportSliceRowPrimary>,
  Simplify<ExternalSupportSliceRowItem>
>;

/**
 * Primary content in *ExternalSupport → Cards → Primary*
 */
export interface ExternalSupportSliceCardsPrimary {
  /**
   * Title field in *ExternalSupport → Cards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.cards.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Intro field in *ExternalSupport → Cards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.cards.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *ExternalSupport → Items*
 */
export interface ExternalSupportSliceCardsItem {
  /**
   * Platform field in *ExternalSupport → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.items[].platform
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  platform: prismic.SelectField<
    "Patreon" | "Kickstarter" | "Ko-fi" | "Discord" | "YouTube" | "Other"
  >;

  /**
   * Button label field in *ExternalSupport → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Short description field in *ExternalSupport → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Destination URL field in *ExternalSupport → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.items[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon / mark field in *ExternalSupport → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Accent color (overrides ember) field in *ExternalSupport → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.items[].accent
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  accent: prismic.ColorField;
}

/**
 * Cards variation for ExternalSupport Slice
 *
 * - **API ID**: `cards`
 * - **Description**: Card grid with icon, description and CTA per platform.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExternalSupportSliceCards = prismic.SharedSliceVariation<
  "cards",
  Simplify<ExternalSupportSliceCardsPrimary>,
  Simplify<ExternalSupportSliceCardsItem>
>;

/**
 * Primary content in *ExternalSupport → Banner → Primary*
 */
export interface ExternalSupportSliceBannerPrimary {
  /**
   * Title field in *ExternalSupport → Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.banner.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Body field in *ExternalSupport → Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.banner.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *ExternalSupport → Items*
 */
export interface ExternalSupportSliceBannerItem {
  /**
   * Platform field in *ExternalSupport → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.items[].platform
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  platform: prismic.SelectField<
    "Patreon" | "Kickstarter" | "Ko-fi" | "Discord" | "YouTube" | "Other"
  >;

  /**
   * Button label field in *ExternalSupport → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Destination URL field in *ExternalSupport → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.items[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Accent color (overrides ember) field in *ExternalSupport → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: external_support.items[].accent
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  accent: prismic.ColorField;
}

/**
 * Banner variation for ExternalSupport Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Single full-width banner with one or two prominent CTAs.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExternalSupportSliceBanner = prismic.SharedSliceVariation<
  "banner",
  Simplify<ExternalSupportSliceBannerPrimary>,
  Simplify<ExternalSupportSliceBannerItem>
>;

/**
 * Slice variation for *ExternalSupport*
 */
type ExternalSupportSliceVariation =
  | ExternalSupportSliceRow
  | ExternalSupportSliceCards
  | ExternalSupportSliceBanner;

/**
 * ExternalSupport Shared Slice
 *
 * - **API ID**: `external_support`
 * - **Description**: Modular block of external CTAs (Patreon, Kickstarter, Ko-fi, Discord, ...). Add platforms over time without touching code.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExternalSupportSlice = prismic.SharedSlice<
  "external_support",
  ExternalSupportSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CharacterDocument,
      CharacterDocumentData,
      CharacterDocumentDataGalleryItem,
      CharacterDocumentDataRelationsItem,
      CharacterDocumentDataSlicesSlice,
      EpisodeDocument,
      EpisodeDocumentData,
      EpisodeDocumentDataTagsItem,
      EpisodeDocumentDataCharactersItem,
      EpisodeDocumentDataSlicesSlice,
      EpisodesIndexDocument,
      EpisodesIndexDocumentData,
      EpisodesIndexDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataHeroCtaItem,
      HomeDocumentDataFeaturedEpisodesItem,
      HomeDocumentDataSlicesSlice,
      LoreEntryDocument,
      LoreEntryDocumentData,
      LoreEntryDocumentDataSlicesSlice,
      NavDocument,
      NavDocumentData,
      NavDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataPrimaryLinksItem,
      NavigationDocumentDataSecondaryLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataBrandItem,
      SettingsDocumentDataSocialLinksItem,
      SettingsDocumentDataStoreLinksItem,
      SettingsDocumentDataNewsletterItem,
      TestDocument,
      TestDocumentData,
      TestDocumentDataSlicesSlice,
      AllDocumentTypes,
      ExternalSupportSlice,
      ExternalSupportSliceRowPrimary,
      ExternalSupportSliceRowItem,
      ExternalSupportSliceCardsPrimary,
      ExternalSupportSliceCardsItem,
      ExternalSupportSliceBannerPrimary,
      ExternalSupportSliceBannerItem,
      ExternalSupportSliceVariation,
      ExternalSupportSliceRow,
      ExternalSupportSliceCards,
      ExternalSupportSliceBanner,
    };
  }
}
