// Code generated by Slice Machine. DO NOT EDIT.
// (After running `npm run slicemachine` and saving, this file will be
// regenerated. The line you must verify is `external_support` is present.)

import dynamic from "next/dynamic";

export const components = {
  callout: dynamic(() => import("./callout")),
  character_grid: dynamic(() => import("./character_grid")),
  cta_block: dynamic(() => import("./cta_block")),
  external_support: dynamic(() => import("./external_support")),
  feature_grid: dynamic(() => import("./feature_grid")),
  gallery: dynamic(() => import("./gallery")),
  image_cards: dynamic(() => import("./image_cards")),
  image_full: dynamic(() => import("./image_full")),
  image_ticker: dynamic(() => import("./image_ticker")),
  lore_section: dynamic(() => import("./lore_section")),
  newsletter: dynamic(() => import("./newsletter")),
  parallax_hero: dynamic(() => import("./parallax_hero")),
  quote: dynamic(() => import("./quote")),
  text_with_image: dynamic(() => import("./text_with_image")),
};
