// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  callout: dynamic(() => import("./callout")),
  character_grid: dynamic(() => import("./character_grid")),
  cta_block: dynamic(() => import("./cta_block")),
  episode_divider: dynamic(() => import("./episode_divider")),
  episode_panel: dynamic(() => import("./episode_panel")),
  episode_text_beat: dynamic(() => import("./episode_text_beat")),
  external_support: dynamic(() => import("./external_support")),
  feature_grid: dynamic(() => import("./feature_grid")),
  hero: dynamic(() => import("./hero")),
  image_cards: dynamic(() => import("./image_cards")),
  image_full: dynamic(() => import("./image_full")),
  image_gallery: dynamic(() => import("./image_gallery")),
  image_ticker: dynamic(() => import("./image_ticker")),
  lore_section: dynamic(() => import("./lore_section")),
  newsletter_embed: dynamic(() => import("./newsletter_embed")),
  parallax_hero: dynamic(() => import("./parallax_hero")),
  quote: dynamic(() => import("./quote")),
  text_with_image: dynamic(() => import("./text_with_image")),
};
