// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
    callout: dynamic(() => import('./Callout')),
    character_grid: dynamic(() => import('./CharacterGrid')),
    character_profile: dynamic(() => import('./CharacterProfile')),
    cta: dynamic(() => import('./Cta')),
    episode_divider: dynamic(() => import('./EpisodeDivider')),
    episode_panel: dynamic(() => import('./EpisodePanel')),
    episode_text_beat: dynamic(() => import('./EpisodeTextBeat')),
    feature_grid: dynamic(() => import('./FeatureGrid')),
    gallery: dynamic(() => import('./Gallery')),
    hero: dynamic(() => import('./Hero')),
    hero_project: dynamic(() => import('./HeroProject')),
    image: dynamic(() => import('./Image')),
    image_cards: dynamic(() => import('./ImageCards')),
    image_full: dynamic(() => import('./ImageFull')),
    lore_section: dynamic(() => import('./LoreSection')),
    newsletter_embed: dynamic(() => import('./NewsletterEmbed')),
    quote: dynamic(() => import('./Quote')),
    text: dynamic(() => import('./Text')),
    text_with_image: dynamic(() => import('./TextWithImage'))
};
