/* Sample content — placeholders. En producción esta data viene de Prismic. */
const HOTC_SAMPLE = {
  hero: {
    kicker_en: "Updates Sundays",
    kicker_es: "Domingos · Capítulo nuevo",
    bgImage: "../../assets/hero-keyart-placeholder.svg",
    bgVideo: null,           // p.ej. "../../assets/hero.mp4"
    foreground: null,        // p.ej. "../../assets/hero-character.png" (PNG con alpha)
  },

  ticker: [
    "../../assets/comic-panel-placeholder.svg",
    "../../assets/character-portrait-placeholder.svg",
    "../../assets/comic-panel-placeholder.svg",
    "../../assets/hero-keyart-placeholder.svg",
    "../../assets/comic-panel-placeholder.svg",
    "../../assets/character-portrait-placeholder.svg",
  ],

  characters: [
    { slug: "mira", name: "Mira", role: "Heir · Living",
      portrait: "../../assets/character-portrait-placeholder.svg",
      cover: "../../assets/hero-keyart-placeholder.svg",
      epithet: "Cartographer's apprentice; the only living descendant of the Ember-tongue line.",
      attributes: [
        { label: "Lineage", value: "Ember-tongue" },
        { label: "Status",  value: "Living" },
        { label: "First seen", value: "Ch. 01" },
        { label: "Carries", value: "Compass" },
      ],
      bio: [
        "Mira grew up in Ash-Hollow, a town built where the second pantheon fell. She was raised by her grandmother, who taught her to read maps before she could read words.",
        "She doesn't speak about the fire that took her parents. She speaks, often, about her grandfather's compass — a gift the year the gods left, which has not pointed north since.",
      ],
      gallery: [
        "../../assets/comic-panel-placeholder.svg",
        "../../assets/comic-panel-placeholder.svg",
        "../../assets/comic-panel-placeholder.svg",
      ],
    },
    { slug: "kael", name: "Kael", role: "Cartographer",
      portrait: "../../assets/character-portrait-placeholder.svg",
      cover: "../../assets/hero-keyart-placeholder.svg",
      epithet: "Walks the southern road; the last to remember its names.",
      attributes: [
        { label: "Lineage", value: "Unknown" },
        { label: "Status",  value: "Living" },
        { label: "First seen", value: "Ch. 03" },
        { label: "Carries", value: "Field journal" },
      ],
      bio: ["Kael walks the southern road that nobody has mapped since the Collapse."],
      gallery: [],
    },
    { slug: "the-archivist", name: "The Archivist", role: "Heir · Lost",
      portrait: "../../assets/character-portrait-placeholder.svg",
      cover: "../../assets/hero-keyart-placeholder.svg",
      epithet: "Keeps every name. Forgets her own.",
      attributes: [{ label: "Lineage", value: "Pale-vow" },{ label: "Status", value: "Lost" }],
      bio: ["She was the youngest priest of the Pale-vow when the Collapse came."],
    },
    { slug: "old-vance", name: "Old Vance", role: "Townfather",
      portrait: "../../assets/character-portrait-placeholder.svg",
      cover: "../../assets/hero-keyart-placeholder.svg",
      epithet: "Ash-Hollow's reluctant elder.",
      attributes: [{ label: "Lineage", value: "None" },{ label: "Status", value: "Living" }],
      bio: ["Vance was a soldier. Now he keeps the lantern lit at the south gate of Ash-Hollow."],
    },
  ],

  // EPISODES — pages: array de URLs a tiras 1080xN. Cada chapter puede tener 1..N tiras.
  episodes: [
    { slug: "ch-12-the-first-heir", number: 12, title: "The First Heir",
      synopsis: "Mira returns to the ruins her mother forbade her to enter.",
      publishedOn: "Sun May 4, 2026", isNew: true,
      cover: "../../assets/comic-panel-placeholder.svg",
      pages: [
        { src: "../../assets/comic-panel-placeholder.svg", width: 1080, height: 1620, alt: "Page 1" },
        { src: "../../assets/comic-panel-placeholder.svg", width: 1080, height: 1620, alt: "Page 2" },
        { src: "../../assets/comic-panel-placeholder.svg", width: 1080, height: 1620, alt: "Page 3" },
      ],
    },
    { slug: "ch-11-a-gods-length-silence", number: 11, title: "A god's-length silence",
      synopsis: "The cartographer learns why the southern road is unmapped.",
      publishedOn: "Sun Apr 27, 2026", isNew: false,
      cover: "../../assets/comic-panel-placeholder.svg",
      pages: [{ src: "../../assets/comic-panel-placeholder.svg", width: 1080, height: 1620 }],
    },
    { slug: "ch-10-the-lantern-keeper", number: 10, title: "The lantern-keeper",
      synopsis: "Old Vance keeps a vigil he won't explain.",
      publishedOn: "Sun Apr 20, 2026", isNew: false,
      cover: "../../assets/comic-panel-placeholder.svg",
      pages: [{ src: "../../assets/comic-panel-placeholder.svg", width: 1080, height: 1620 }],
    },
    { slug: "ch-09-pale-vow", number: 9, title: "Pale-vow",
      synopsis: "An archivist writes a name she does not recognize.",
      publishedOn: "Sun Apr 13, 2026", isNew: false,
      cover: "../../assets/comic-panel-placeholder.svg",
      pages: [{ src: "../../assets/comic-panel-placeholder.svg", width: 1080, height: 1620 }],
    },
    { slug: "ch-08-ember-tongue", number: 8, title: "Ember-tongue",
      synopsis: "Mira learns what her family was, before.",
      publishedOn: "Sun Apr 6, 2026", isNew: false,
      cover: "../../assets/comic-panel-placeholder.svg",
      pages: [{ src: "../../assets/comic-panel-placeholder.svg", width: 1080, height: 1620 }],
    },
    { slug: "ch-07-second-pantheon", number: 7, title: "The second pantheon",
      synopsis: "A tale told by a dying priest in the rain.",
      publishedOn: "Sun Mar 30, 2026", isNew: false,
      cover: "../../assets/comic-panel-placeholder.svg",
      pages: [{ src: "../../assets/comic-panel-placeholder.svg", width: 1080, height: 1620 }],
    },
  ],

  worldbuilding: {
    environments: [
      { slug: "ash-hollow", name: "Ash-Hollow", role: "Town · South",
        portrait: "../../assets/hero-keyart-placeholder.svg",
        cover: "../../assets/hero-keyart-placeholder.svg",
        epithet: "Built on the bones of the second pantheon.",
        kind: "Environment",
        body: ["Founded the year the gods left, on the broken altar where the second pantheon fell. Lit at night by a single lantern at the south gate."],
        gallery: ["../../assets/comic-panel-placeholder.svg","../../assets/comic-panel-placeholder.svg"] },
      { slug: "southern-road", name: "The Southern Road", role: "Region",
        portrait: "../../assets/comic-panel-placeholder.svg",
        cover: "../../assets/hero-keyart-placeholder.svg",
        epithet: "Older than the maps that tried to draw it.",
        kind: "Environment",
        body: ["Nobody has mapped the southern road since the Collapse. Kael walks it once a season, and brings back names."] },
      { slug: "the-pale-archive", name: "The Pale Archive", role: "Site",
        portrait: "../../assets/character-portrait-placeholder.svg",
        cover: "../../assets/hero-keyart-placeholder.svg",
        epithet: "A library of names nobody remembers.",
        kind: "Environment",
        body: ["The last priest of the Pale-vow lives here. She writes names on the walls until the walls run out."] },
    ],
    props: [
      { slug: "compass", name: "Mira's Compass", role: "Heirloom",
        portrait: "../../assets/character-portrait-placeholder.svg", cover: "../../assets/hero-keyart-placeholder.svg",
        epithet: "Has not pointed north since the gods left.", kind: "Prop",
        body: ["Made the year the second pantheon fell. Points to whatever Mira is about to lose."] },
      { slug: "lantern",  name: "South-gate Lantern", role: "Vigil",
        portrait: "../../assets/comic-panel-placeholder.svg", cover: "../../assets/hero-keyart-placeholder.svg",
        epithet: "Lit every night, for reasons Vance won't explain.", kind: "Prop" },
      { slug: "ledger",   name: "The Archivist's Ledger", role: "Document",
        portrait: "../../assets/character-portrait-placeholder.svg", cover: "../../assets/hero-keyart-placeholder.svg",
        epithet: "Names of everyone she's forgotten.", kind: "Prop" },
    ],
    illustrations: [
      { slug: "ill-01", title: "Ash-Hollow at Dusk", role: "Cover · 2026",
        portrait: "../../assets/hero-keyart-placeholder.svg", cover: "../../assets/hero-keyart-placeholder.svg",
        epithet: "Print run of 200, signed.", kind: "Illustration" },
      { slug: "ill-02", title: "The Walk South", role: "Sketch · 2025",
        portrait: "../../assets/comic-panel-placeholder.svg", cover: "../../assets/hero-keyart-placeholder.svg",
        epithet: "Charcoal study from the Kael chapters.", kind: "Illustration" },
      { slug: "ill-03", title: "The Pale-vow", role: "Cover · 2025",
        portrait: "../../assets/comic-panel-placeholder.svg", cover: "../../assets/hero-keyart-placeholder.svg",
        epithet: "Variant cover for the print collection.", kind: "Illustration" },
    ],
  },

  store: [
    { slug: "vol-01", category: "Print Volume", title: "Heirs of the Collapse — Vol. 01",
      desc: "First six chapters, hardcover, 184 pages. Signed bookplate.",
      price: "€32", image: "../../assets/hero-keyart-placeholder.svg", tag: "New" },
    { slug: "print-ash", category: "Art Print · A3", title: "Ash-Hollow at Dusk",
      desc: "Giclée print on heavyweight matte. Limited run of 200.",
      price: "€28", image: "../../assets/comic-panel-placeholder.svg" },
    { slug: "tee-ember", category: "Apparel", title: "Ember-tongue Tee",
      desc: "Heavyweight cotton, screen-printed. Sandra approved.",
      price: "€26", image: "../../assets/character-portrait-placeholder.svg", tag: "Limited" },
    { slug: "sticker-pack", category: "Stickers", title: "Sigil Sticker Pack",
      desc: "All four surviving sigils. Vinyl, weatherproof.",
      price: "€8", image: "../../assets/comic-panel-placeholder.svg", outOfStock: true },
  ],
};

window.HOTC_SAMPLE = HOTC_SAMPLE;
