name: Publish Episode

on:
  repository_dispatch:
    types: [prismic-publish-episode]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: node scripts/publish-episode.mjs
        env:
          PRISMIC_REPOSITORY: ${{ secrets.PRISMIC_REPOSITORY }}
          PRISMIC_ACCESS_TOKEN: ${{ secrets.PRISMIC_ACCESS_TOKEN }}
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
